version: "3"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.SQL
    container_name: postgres
    volumes:
      - data-volume:/var/lib/postgresql/data/:rw
    environment:
      - POSTGRES_USER=tonyliu666
      - POSTGRES_PASSWORD=t870101
      - POSTGRES_HOST=postgres 
      - POSTGRES_PORT=5432 
      - POSTGRES_DB=db 
      - POSTGRES_INITDB_ARGS= --encoding=UTF-8
    restart: unless-stopped
    expose:
      - "5432"
    networks: 
      - turingmysql

  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 4gb
    container_name: chrome
    expose : 
      - "4444"
    networks:
      - chrome_net
  flask-web:
    image: main
    container_name: template_flask
    depends_on:
      - db
      - chrome
    links:
      - db
      - chrome
    volumes:
      - type: volume
        source: vol
        target: /app
    command: >
      sh -c "
        python /app/web/src/main.py
      "  
    environment:
      - POSTGRES_USER=tonyliu666
      - POSTGRES_PASSWORD=t870101
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432 
      - POSTGRES_DB=db
      - SELENIUM_REMOTE_HOST=chrome
    ports:
      - "8080:80"
    networks: 
      - turingmysql
      - chrome_net
      # - flask
      # - sel_net
volumes:
  data-volume:
  vol:
networks:
  turingmysql:
  # flask:
  #   driver: bridge
  chrome_net:
